- name: "Determine 'latest' version release"
  when: vaultwarden_version == "latest"
  block:
    - name: "Get latest vaultwarden release metadata"
      ansible.builtin.uri:
        url: https://api.github.com/repos/dani-garcia/vaultwarden/releases/latest
        return_content: true
      register: vaultwarden_remote_metadata
      when: not ansible_check_mode

    - name: "Fail if running in check mode without versions set."
      ansible.builtin.fail:
        msg: |
          "You are running this playbook in check mode:
            Please set the Vaultwarden and webvault version with the variable 'vaultwarden_version' and
            'vaultwarden_webvault_version', because the URI module cannot detect the latest version in this mode."
      when: ansible_check_mode and (vaultwarden_version == 'latest')

    - name: "Set fact latest vaultwarden release"
      ansible.builtin.set_fact:
        vaultwarden_remote_version: "{{ vaultwarden_remote_metadata.json.tag_name[1:] }}"
      when: not ansible_check_mode

    - name: "Get latest vaultwarden webvault release metadata"
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/dani-garcia/vaultwarden/{{ vaultwarden_remote_version }}/docker/Dockerfile.j2
        return_content: true
      register: vaultwarden__webvault_remote_metadata
      when: not ansible_check_mode


    - name: "Set fact latest vaultwarden webvault release"
      ansible.builtin.set_fact:
        vaultwarden_webvault_remote_version: |
          "{{ vaultwarden_webvault_remote_metadata |
          regex_search('set vault_version ', multiline=true) | regex_replace('.*"([^"]+)".*', '\1') }}"
      when: not ansible_check_mode

    - name: "Set vaultwarden version target (latest)"
      ansible.builtin.set_fact:
        vaultwarden_version_target: "{{ vaultwarden_remote_version }}"
        vaultwarden_webvault_version_target: "{{ vaultwarden_webvault_remote_version }}"
      when: not ansible_check_mode

- name: "Set vaultwarden version target {{ vaultwarden_version }}"
  ansible.builtin.set_fact:
    vaultwarden_version_target: "{{ vaultwarden_version }}"
    vaultwarden_webvault_version_target: "{{ vaultwarden_webvault_version }}"
  when: vaultwarden_version != "latest"
