---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  tasks:
    - name: "Include vaultwarden"
      ansible.builtin.include_role:
        name: "ansible-role-vaultwarden"

  post_tasks:
    - name: DEBUG dump vaultwarden journal
      ansible.builtin.command: journalctl -u vaultwarden --no-pager -n 100
      changed_when: false
      register: _debug_journal

    - name: DEBUG show journal
      ansible.builtin.debug:
        var: _debug_journal.stdout_lines
