---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Create fake previous build directory
      ansible.builtin.file:
        path: /opt/vaultwarden/vaultwarden-0.0.0-test/target/release
        state: directory
        mode: u=rwx,go=rx

  tasks:
    - name: "Include vaultwarden"
      ansible.builtin.include_role:
        name: "ansible-role-vaultwarden"
