---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: apt
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - "8000:8000/tcp"
  - name: source
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - "8001:8000/tcp"
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "$MOLECULE_PROJECT_DIRECTORY/.."
  inventory:
    host_vars:
      apt:
        vaultwarden_install_type: "apt"
      source:
        vaultwarden_install_type: "source"
verifier:
  name: ansible
