---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Create fake previous build directory
      ansible.builtin.file:
        path: /opt/vaultwarden/vaultwarden-0.0.0-test/target/release
        state: directory
        mode: u=rwx,go=rx
