---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check fake previous build directory is removed
      ansible.builtin.stat:
        path: /opt/vaultwarden/vaultwarden-0.0.0-test
      register: _vaultwarden_old_build

    - name: Assert previous build directory was removed
      ansible.builtin.assert:
        that: not _vaultwarden_old_build.stat.exists

    - name: List remaining vaultwarden build directories
      ansible.builtin.find:
        paths: /opt/vaultwarden
        patterns: "vaultwarden-*"
        file_type: directory
      register: _vaultwarden_build_dirs

    - name: Assert only the current build directory remains
      ansible.builtin.assert:
        that:
          - _vaultwarden_build_dirs.files | length == 1
          - not (_vaultwarden_build_dirs.files[0].path is match('.*/vaultwarden-[0-9.]+-test$'))
          - _vaultwarden_build_dirs.files[0].path is match('/opt/vaultwarden/vaultwarden-\d+\.\d+\.\d+$')

    - name: Check vaultwarden service is active
      ansible.builtin.systemd:
        name: vaultwarden
      register: _vaultwarden_service

    - name: Assert vaultwarden service is active
      ansible.builtin.assert:
        that: _vaultwarden_service.status.ActiveState == 'active'

    - name: Check vaultwarden responds
      ansible.builtin.uri:
        url: http://localhost:8000/alive
        status_code: 200
      register: _vaultwarden_alive
      retries: 6
      delay: 10
      until: _vaultwarden_alive.status == 200
