name: Ansible Molecule  
on: [push, pull_request]


jobs:
  molecule:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, centos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@5.0.2
        with:
          command: lint
